services:
  - type: web
    name: crm-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd ../frontend
      cp package.prod.json package.json
      npm install --legacy-peer-deps
      npm run build
      cd ../backend
      cp -r ../frontend/dist/* src/static/
    startCommand: gunicorn src.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 